S2 us11 user register
WildCodeSchool-2024-02/php-poec-paris-p2-escapegame pull request #17
Opened 2024-06-06 14:08 UTC by AnnaGosme

- User Register Flow ✍️

Homepage register link -> Register page -> if user does not already exist && password matches confirmPassword -> save in database and redirect to home page.

2024-06-10 10:36 UTC, mickaellambert requested changes

2024-06-10 10:36 UTC, mickaellambert commented on src/Controller/UserController.php
> +    // public function registerNewUser()
Commentaires inutiles

2024-06-10 10:36 UTC, mickaellambert commented on src/Controller/UserController.php
> +    public function registerNewUser()
ici, `register` suffit comme naming

2024-06-10 10:36 UTC, mickaellambert commented on src/Controller/UserController.php
> +            $this->checkUserExistence($data['name'], $data['email']);
Ici, pas besoin de faire une fonction qui fait juste un appel de fonction d'un manager, met directement la fonction de UserManager

2024-06-10 10:36 UTC, mickaellambert commented on src/Controller/UserController.php
> +        if ($this->userManager->userExists($name, $email)) {
Je l'appelerai plus `selectOneByEmail` et pourquoi fournir le nom ?

2024-06-10 10:36 UTC, mickaellambert commented on src/Controller/UserController.php
> +                $this->userManager->save($data['name'], $data['email'], $data['password']);
Si dans les autres managers les fonctions d'ajout s'appellent `insert`, réutilise le même naming

2024-06-10 10:36 UTC, mickaellambert commented on src/Controller/UserController.php
> +    private function sanitizeInput($input)
Pas besoin de faire une fonction pour juste cette ligne

2024-06-10 10:36 UTC, mickaellambert commented on src/Controller/UserController.php
> +    private function checkPasswordMatch($password, $confirmPassword)
Pareil ici, tu peux laisser la logique dans la fonction de route de base

2024-06-10 10:36 UTC, mickaellambert commented on src/Model/UserManager.php
> +    public function userExists($username, $email)
Voir plus haut pour le naming

2024-06-10 10:36 UTC, mickaellambert commented on src/Model/UserManager.php
> +    public function save(string $name, string $email, string $password)
voir plus haut pour le naming

2024-06-10 10:36 UTC, mickaellambert commented on src/routes.php
> +    'register' => ['UserController', 'show'],
C'est bizarre ici, tu devrais avoir une seule route `register` qui gère le cas d'affichage du formulaire ou de validation grâce à un `if ($_SERVER['REQUEST_METHOD'] === 'POST')`

2024-06-11 08:38 UTC, AnnaGosme commented on src/Controller/UserController.php
> +        if ($this->userManager->userExists($name, $email)) {
fonction supprimée -> appelle direct au Manager dans register()

2024-06-11 08:40 UTC, AnnaGosme commented on src/Controller/UserController.php
> +    private function sanitizeInput($input)
Ici problème de grump qui me dit que la complexité (?) de la fonction tout en un est trop élevée (12 alors que max doit être 10)

2024-06-11 11:44 UTC, mickaellambert approved these changes

2024-06-11 11:44 UTC, merged