S1US01 create challenge mvc
WildCodeSchool-2024-02/php-poec-paris-p2-escapegame pull request #7
Opened 2024-05-31 10:25 UTC by Kuriiios

2024-06-03 08:13 UTC, mickaellambert requested changes

2024-06-03 08:13 UTC, mickaellambert commented on src/Controller/ChallengeController.php
> +    public function show(int $id): string
C'est l'US d'affichage d'un challenge ou de création d'un challenge ?

2024-06-03 08:13 UTC, mickaellambert commented on src/Controller/ChallengeController.php
> +        var_dump($challenge);
Attention aux var_dump laissés dans le code

2024-06-03 08:13 UTC, mickaellambert commented on src/Controller/ChallengeController.php
> +        return $this->twig->render('Home/index.html.twig');
Si tu fais un show d'un challenge, tu veux afficher la homepage ?

2024-06-03 08:13 UTC, mickaellambert commented on src/Controller/ChallengeController.php
> +    public function getChallengeType(int $id): array|string
Je comprends pas trop l'intérêt de cette fonction, quel est le but de l'US et donc de la PR ?

2024-06-03 08:13 UTC, mickaellambert commented on src/Controller/ChallengeController.php
> +            die();
Ta fonction retourne soit une vue soit un challenge c'est bizarre

2024-06-03 08:13 UTC, mickaellambert commented on src/Model/ChallengeManager.php
> +    public function selectChallengeType(int $id): array|false
Tu peux utiliser la fonction selectOneById qui existe déjà et venir selectionner le champ type dans tout le tableau de données retourné

2024-06-03 08:13 UTC, mickaellambert commented on src/Model/ChallengeManager.php
> +    public function setAssets(int $roomId, int $id)
Définir les assets grâce à votre architecture de dossier, pas dans votre code

2024-06-03 08:13 UTC, mickaellambert commented on src/Model/Connection.php
> +    public function getConnection(): PDO
Si tu le changes ou il est défini, pense à le changer partout ou il est utilisé

2024-06-03 08:13 UTC, mickaellambert commented on src/routes.php
> +    'challenges/type' => ['ChallengeController', 'displayChallengeLayout', ['id']],
Je vois pas trop l'utilité de cette route

2024-06-03 11:44 UTC, mickaellambert requested changes

2024-06-03 11:44 UTC, mickaellambert commented on src/Model/ChallengeManager.php
> +    public array $assets;
Plus besoin de cette propriété du coup

2024-06-03 11:44 UTC, mickaellambert commented on src/View/Error/error.html.twig
Plus besoin de ce fichier du coup

2024-06-03 11:44 UTC, mickaellambert commented on src/View/Home/index.html.twig
Vous voulez garder une page d'accueil ? Si oui, ok pour ce fichier sinon il peut dégager aussi

2024-06-03 12:48 UTC, Kuriiios commented on src/View/Home/index.html.twig
Oui, le menu de départ sera la page d'accueil

2024-06-04 07:30 UTC, mickaellambert approved these changes

2024-06-04 07:30 UTC, merged