S1 us02 challenge puzzle
WildCodeSchool-2024-02/php-poec-paris-p2-escapegame pull request #9
Opened 2024-06-03 13:07 UTC by AnnaGosme

- functional puzzle 🧩
- id2=> 6 pieces
- id6 => 9 pieces
- id9 => 9 pieces

- managed edge cases : 
    - modifying tile position 🔀
    - disable putting multiple tiles on same square 🚫

- add in sidebar for puzzle rearrangement  🍫

- correct database answers in challenges ✅
- add challenge names to id2, id6, id9 📇
    
- styling not done but functionality of :
- routing user win => button to move to next challenge (temporary ?) 🏆
- routing user loses => button return to puzzle 🔁

- clean routes 🧼

2024-06-04 08:12 UTC, mickaellambert requested changes

2024-06-04 08:12 UTC, mickaellambert commented on src/Controller/ChallengeController.php
> +    public $images = [
Toute cette partie là devrait se faire directement dans le front, pas besoin de créer des choses dans le back ici

2024-06-04 08:12 UTC, mickaellambert commented on src/Controller/ChallengeController.php
> +    public function shuffleImages()
Pareil pour ce bloc, tu peux faire tout ça en front

2024-06-04 08:12 UTC, mickaellambert commented on src/Controller/ChallengeController.php
> +    public array $data;
A quoi sert cette propriété ?

2024-06-04 08:12 UTC, mickaellambert commented on src/View/Challenges/puzzle.html.twig
> +                    {% for image in images %}
Ici, au lieu de récupérer des données du back, tu peux juste faire une boucle de 1 à 6, randomiser un nombre entre 1 et 6 à chaque passage et utiliser le challenge.id pour savoir dans quel dossier aller chercher tes images 

Tu gardes ta logique de construction front dans ton front et tu la mélanges pas avec le back

2024-06-04 08:12 UTC, mickaellambert commented on src/View/Challenges/puzzle.html.twig
> +        input.type = "hidden";
Tu pourrais le créer de base dans le HTML et venir modifier sa valeur plutôt que de le créer à la volée

2024-06-04 08:12 UTC, mickaellambert commented on src/View/Challenges/puzzle.html.twig
> +        console.log(userSolution)
Attention à tous les console.log laissés dans le code

2024-06-04 08:12 UTC, mickaellambert commented on src/View/Challenges/puzzle.html.twig
> +<script>
Essaie d'espacer un peu plus ton code javascript pour qu'il soit plus lisible. Réunis les fonctions en bas, la logique en haut

2024-06-04 08:12 UTC, mickaellambert commented on src/Controller/ChallengeController.php
> +            $userSolution = array_map(function ($filename) {
Est ce que tu ne pourrais pas plutôt ne pas envoyer le nom complet de l'image avec l'extension dans la solution plutôt que devoir le remplacer lors de la récupération ?

2024-06-04 08:12 UTC, mickaellambert commented on src/Controller/ChallengeController.php
> +    public function validate(int $id)
Ici, j'ai l'impression que tu crées la route qui va permettre de valider un challenge, et tu mets beaucoup de logique du challenge de type puzzle dedans. 
Il faudrait que t'arrives, quelque soit le type de challenge, à : 

- Récupérer la réponse (formater la réponse à l'envoi pour qu'elle soit similaire quelque soit le type de challenge)
- Nettoyer la réponse comme tu l'as fait avec trim et htmlentities
- Vérifier que la réponse donnée est égale à la réponse du challenge

2024-06-04 08:12 UTC, mickaellambert commented on src/Controller/ChallengeController.php
> +            $correctAnswer = $challengeManager->selectChallengeAnswer($id);
Pas besoin de créer une fonction spécifique ici, tu peux juste utiliser le `selectOneById` qui existe déjà et accéder à la clé `answer` de ton `challenge`

2024-06-04 08:12 UTC, mickaellambert commented on src/Controller/ChallengeController.php
> +                $isCorrect = $userSolutionString === $correctAnswer['answer'];
En vérifiant l'égalité entre deux strings, tu vérifies aussi que la taille est similaire, pas besoin de faire les deux tests

2024-06-04 08:12 UTC, mickaellambert commented on src/Controller/ChallengeController.php
> +                throw new Exception('Too few arguments');
Pas d'exceptions pour l'instant

2024-06-04 08:12 UTC, mickaellambert commented on src/Model/ChallengeManager.php
> +    public array $assets;
Pas besoin de cette propriété

2024-06-04 08:12 UTC, mickaellambert commented on src/Model/ChallengeManager.php
> +    public function selectChallengeType(int $id): array|false
Pas besoin de cette fonction, tu peux récupérer le type en utilisant la fonction `selectOneById` déjà existante et en accédant à la clé `type`

2024-06-04 08:12 UTC, mickaellambert commented on src/Model/ChallengeManager.php
> +    public function selectChallengeAnswer(int $id): array|false
idem

2024-06-04 15:43 UTC, AnnaGosme commented on src/Controller/ChallengeController.php
> +            $userSolution = array_map(function ($filename) {
😣 pour l'instant je laisse tel quel ... TODO plus tard

2024-06-05 08:55 UTC, mickaellambert requested changes

2024-06-05 08:55 UTC, mickaellambert commented on src/Controller/ChallengeController.php
> +    public function prepareUserSolution($userSolution)
Ici il faudrait passer cette fonction en private si possible

2024-06-05 08:55 UTC, mickaellambert commented on src/Controller/ChallengeController.php
> +        $jsonString = $userSolution;
Pas besoin de cette ligne

2024-06-05 08:55 UTC, mickaellambert commented on src/Controller/ChallengeController.php
> +        $userSolution = array_map('trim', array_map('htmlentities', $userSolution));
Peux tu essayer d'aérer un peu plus le code dans cette fonction pour qu'il soit plus lisible stp ?

2024-06-05 08:55 UTC, mickaellambert commented on src/Controller/ChallengeController.php
> +    public function validate(int $id)
```  
 public function validate(int $id)
    {
        $userAnswer = array_map('trim', array_map('htmlentities', $_POST['user_answer']));

        $challengeManager = new ChallengeManager();
        $challenge = $challengeManager->selectOneById($id);

        return $this->twig->render('Challenges/validate.html.twig', [
            'isCorrect' => $userAnswer === $challenge['answer'],
            'challenge' => $challenge
        ]);
    }
 ```

2024-06-05 10:42 UTC, mickaellambert approved these changes

2024-06-05 10:43 UTC, merged